// packages/create/overlays/react/src/App.tsx
import { useLayoutEffect, useMemo, useRef, useState } from 'react';
import { DOMRenderer, type DOMMount } from '@gneh/renderer-dom';
import type { View } from '@gneh/core';
import type { Story } from '@gneh/runtime';

function StoryView({ view }: { view: View[] }) {
  const host = useRef<HTMLElement>(null);
  const renderer = useMemo(() => new DOMRenderer(), []);
  const mount = useRef<DOMMount | undefined>(undefined);
  useLayoutEffect(() => {
    if (!host.current) return;
    if (mount.current) renderer.update(mount.current, view);
    else mount.current = renderer.mount(host.current, view);
  }, [renderer, view]);
  useLayoutEffect(
    () => () => {
      if (mount.current) renderer.dispose(mount.current);
      mount.current = undefined;
    },
    [renderer],
  );
  return <article ref={host} />;
}

export function App({ story }: { story: Story }) {
  const [view, setView] = useState(() => story.view);
  const [, redraw] = useState(0);
  useLayoutEffect(
    () =>
      story.subscribe((next) => {
        setView(next);
        redraw((value) => value + 1);
      }),
    [story],
  );
  return (
    <div className="gneh-app" data-environment="story-flow">
      <header className="toolbar">
        <strong>
          GNĒH <small>React starter</small>
        </strong>
        <button onClick={() => story.undo()} disabled={!story.canUndo}>
          Undo
        </button>
        <button onClick={() => story.redo()} disabled={!story.canRedo}>
          Redo
        </button>
        <button onClick={() => localStorage.setItem('gneh:save', story.save())}>Save</button>
        <button
          onClick={() => {
            const saved = localStorage.getItem('gneh:save');
            if (saved) story.load(saved);
          }}
        >
          Load
        </button>
      </header>
      <div className="layout">
        <aside>
          <p>PASSAGES</p>
          <nav>
            {[...story.fragments.values()]
              .filter(
                (fragment) =>
                  fragment.metadata.nav !== false &&
                  !(Array.isArray(fragment.metadata.params) && fragment.metadata.params.length),
              )
              .map((fragment) => (
                <button
                  key={fragment.id}
                  aria-current={fragment.id === story.current ? 'page' : undefined}
                  onClick={() => story.navigate(fragment.id)}
                >
                  {String(fragment.metadata.title ?? fragment.id)}
                </button>
              ))}
          </nav>
        </aside>
        <main>
          <div className="route">{story.current}</div>
          <StoryView view={view} />
        </main>
      </div>
    </div>
  );
}

// packages/create/overlays/vue/src/App.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, shallowRef } from 'vue';
import { DOMRenderer, type DOMMount } from '@gneh/renderer-dom';
import type { Story } from '@gneh/runtime';

const { story } = defineProps<{ story: Story }>();
const host = ref<HTMLElement>();
const current = ref(story.current);
const revision = ref(0);
const renderer = new DOMRenderer();
const mount = shallowRef<DOMMount>();
let unsubscribe: (() => void) | undefined;

function save() {
  localStorage.setItem('gneh:save', story.save());
}

function load() {
  const saved = localStorage.getItem('gneh:save');
  if (saved) story.load(saved);
}

onMounted(() => {
  unsubscribe = story.subscribe((view) => {
    if (!host.value) return;
    if (mount.value) renderer.update(mount.value, view);
    else mount.value = renderer.mount(host.value, view);
    current.value = story.current;
    revision.value++;
  });
});
onBeforeUnmount(() => {
  unsubscribe?.();
  if (mount.value) renderer.dispose(mount.value);
});
</script>

<template>
  <div class="gneh-app" data-environment="story-flow" :data-revision="revision">
    <header class="toolbar">
      <strong>GNĒH <small>Vue starter</small></strong>
      <button :disabled="!story.canUndo" @click="story.undo()">Undo</button
      ><button :disabled="!story.canRedo" @click="story.redo()">Redo</button>
      <button @click="save">Save</button>
      <button @click="load">Load</button>
    </header>
    <div class="layout">
      <aside>
        <p>PASSAGES</p>
        <nav>
          <button
            v-for="fragment in [...story.fragments.values()].filter(
              (item) =>
                item.metadata.nav !== false && !(Array.isArray(item.metadata.params) && item.metadata.params.length),
            )"
            :key="fragment.id"
            :aria-current="fragment.id === current ? 'page' : undefined"
            @click="story.navigate(fragment.id)"
          >
            {{ String(fragment.metadata.title ?? fragment.id) }}
          </button>
        </nav>
      </aside>
      <main>
        <div class="route">{{ current }}</div>
        <article ref="host" />
      </main>
    </div>
  </div>
</template>
