// packages/create/overlays/preact/src/App.tsx
import { useEffect, useMemo, useRef, useState } from 'preact/hooks';
import { DOMRenderer, type DOMMount } from '@gneh/renderer-dom';
import type { View } from '@gneh/core';
import primary, { fragments } from './story/main.inkdown';
import { createStory } from './story';

function StoryView({ view }: { view: View[] }) {
  const host = useRef<HTMLElement>(null);
  const renderer = useMemo(() => new DOMRenderer(), []);
  const mount = useRef<DOMMount | undefined>(undefined);
  useEffect(() => {
    if (!host.current) return;
    if (mount.current) renderer.update(mount.current, view);
    else mount.current = renderer.mount(host.current, view);
  }, [renderer, view]);
  useEffect(
    () => () => {
      if (mount.current) renderer.dispose(mount.current);
      mount.current = undefined;
    },
    [renderer],
  );
  return <article ref={host} />;
}

export function App() {
  const story = useMemo(
    () => createStory(Object.values(fragments), { entry: primary.id, state: { visits: 0 } }).start(),
    [],
  );
  const [view, setView] = useState(story.view);
  const [, redraw] = useState(0);
  useEffect(
    () =>
      story.subscribe((next) => {
        setView(next);
        redraw((value) => value + 1);
      }),
    [story],
  );
  useEffect(() => () => story.dispose(), [story]);
  return (
    <div class="gneh-app" data-environment="story-flow">
      <header class="toolbar">
        <strong>
          GNĒH <small>Preact starter</small>
        </strong>
        <button onClick={() => story.undo()} disabled={!story.canUndo}>
          Undo
        </button>
        <button onClick={() => story.redo()} disabled={!story.canRedo}>
          Redo
        </button>
      </header>
      <div class="layout">
        <aside>
          <p>PASSAGES</p>
          <nav>
            {[...story.fragments.values()]
              .filter((fragment) => fragment.metadata.nav !== false)
              .map((fragment) => (
                <button
                  key={fragment.id}
                  aria-current={fragment.id === story.current ? 'page' : undefined}
                  onClick={() => story.navigate(fragment.id)}
                >
                  {String(fragment.metadata.title ?? fragment.id)}
                </button>
              ))}
          </nav>
        </aside>
        <main>
          <div class="route">{story.current}</div>
          <StoryView view={view} />
        </main>
      </div>
    </div>
  );
}

// packages/create/overlays/vue/src/App.vue
<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, shallowRef } from 'vue';
import { DOMRenderer, type DOMMount } from '@gneh/renderer-dom';
import primary, { fragments } from './story/main.inkdown';
import { createStory } from './story';

const story = createStory(Object.values(fragments), { entry: primary.id, state: { visits: 0 } }).start();
const host = ref<HTMLElement>();
const current = ref(story.current);
const revision = ref(0);
const renderer = new DOMRenderer();
const mount = shallowRef<DOMMount>();
let unsubscribe: (() => void) | undefined;
onMounted(() => {
  unsubscribe = story.subscribe((view) => {
    if (!host.value) return;
    if (mount.value) renderer.update(mount.value, view);
    else mount.value = renderer.mount(host.value, view);
    current.value = story.current;
    revision.value++;
  });
});
onBeforeUnmount(() => {
  unsubscribe?.();
  if (mount.value) renderer.dispose(mount.value);
  story.dispose();
});
</script>

<template>
  <div class="gneh-app" data-environment="story-flow" :data-revision="revision">
    <header class="toolbar">
      <strong>GNĒH <small>Vue starter</small></strong>
      <button :disabled="!story.canUndo" @click="story.undo()">Undo</button
      ><button :disabled="!story.canRedo" @click="story.redo()">Redo</button>
    </header>
    <div class="layout">
      <aside>
        <p>PASSAGES</p>
        <nav>
          <button
            v-for="fragment in [...story.fragments.values()].filter((item) => item.metadata.nav !== false)"
            :key="fragment.id"
            :aria-current="fragment.id === current ? 'page' : undefined"
            @click="story.navigate(fragment.id)"
          >
            {{ String(fragment.metadata.title ?? fragment.id) }}
          </button>
        </nav>
      </aside>
      <main>
        <div class="route">{{ current }}</div>
        <article ref="host" />
      </main>
    </div>
  </div>
</template>
